#ifndef __BUFFIO_ENUM__
#define __BUFFIO_ENUM__

enum BUFFIO_ROUTINE_STATUS {
  BUFFIO_ROUTINE_STATUS_WAITING = 21,
  BUFFIO_ROUTINE_STATUS_EXECUTING,
  BUFFIO_ROUTINE_STATUS_YIELD,
  BUFFIO_ROUTINE_STATUS_ERROR,
  BUFFIO_ROUTINE_STATUS_PAUSED,
  BUFFIO_ROUTINE_STATUS_DONE,
  BUFFIO_ROUTINE_STATUS_EHANDLER,
  BUFFIO_ROUTINE_STATUS_UNHANDLED_EXCEPTION,
  BUFFIO_ROUTINE_STATUS_UNHANDLED_EXCEPTION_DONE,
};

enum BUFFIO_TASK_STATUS {
  BUFFIO_TASK_SWAPPED = 31,
  BUFFIO_TASK_WAITER_EXCEPTION_WAITING,
  BUFFIO_TASK_WAITER_EXCEPTION_DONE,
  BUFFIO_TASK_WAITER_NONE,
};

enum BUFFIO_QUEUE_STATUS {
  BUFFIO_QUEUE_STATUS_ERROR = 40,
  BUFFIO_QUEUE_STATUS_SUCCESS = 41,
  BUFFIO_QUEUE_STATUS_YIELD,
  BUFFIO_QUEUE_STATUS_EMPTY,
  BUFFIO_QUEUE_STATUS_SHUTDOWN,
  BUFFIO_QUEUE_STATUS_CONTINUE,
};

enum BUFFIO_EVENTLOOP_TYPE {
  BUFFIO_EVENTLOOP_SYNC = 50, // use this to block main thread
  BUFFIO_EVENTLOOP_ASYNC,     // use this to launch a thread;
 // BUFFIO_EVENTLOOP_SEPERATE,  // use this to create a seperate process from main
  BUFFIO_EVENTLOOP_DOWN,      // indicates eventloop is not running

};

enum BUFFIO_ACCEPT_STATUS {
  BUFFIO_ACCEPT_STATUS_ERROR = 60,
  BUFFIO_ACCEPT_STATUS_SUCCESS = 61,
  BUFFIO_ACCEPT_STATUS_NA,
  BUFFFIO_ACCEPT_STATUS_NO_HANDLER,
};

#endif
