#ifndef __BUFFIO_ENUM__
#define __BUFFIO_ENUM__

enum BUFFIO_ROUTINE_STATUS {
  BUFFIO_ROUTINE_STATUS_WAITING = 21,
  BUFFIO_ROUTINE_STATUS_EXECUTING,
  BUFFIO_ROUTINE_STATUS_YIELD,
  BUFFIO_ROUTINE_STATUS_ERROR,
  BUFFIO_ROUTINE_STATUS_PAUSED,
  BUFFIO_ROUTINE_STATUS_PUSH_TASK,
  BUFFIO_ROUTINE_STATUS_DONE,
  BUFFIO_ROUTINE_STATUS_UNHANDLED_EXCEPTION,
  BUFFIO_ROUTINE_STATUS_WAITING_IO,
};

enum BUFFIO_TASK_STATUS {
  BUFFIO_TASK_SWAPPED = 31,
  BUFFIO_TASK_WAITER_EXCEPTION_WAITING,
  BUFFIO_TASK_WAITER_EXCEPTION_DONE,
  BUFFIO_TASK_WAITER_NONE,
};

enum BUFFIO_QUEUE_STATUS {
  BUFFIO_QUEUE_STATUS_ERROR = 40,
  BUFFIO_QUEUE_STATUS_SUCCESS = 41,
  BUFFIO_QUEUE_STATUS_YIELD,
  BUFFIO_QUEUE_STATUS_EMPTY,
  BUFFIO_QUEUE_STATUS_SHUTDOWN,
  BUFFIO_QUEUE_STATUS_CONTINUE,
};

enum BUFFIO_EVENTLOOP_TYPE {
  BUFFIO_EVENTLOOP_SYNC = 50, // use this to block main thread
  BUFFIO_EVENTLOOP_ASYNC,     // use this to launch a thread;
 // BUFFIO_EVENTLOOP_SEPERATE,  // use this to create a seperate process from main
  BUFFIO_EVENTLOOP_DOWN,      // indicates eventloop is not running

};

enum BUFFIO_ACCEPT_STATUS {
  BUFFIO_ACCEPT_STATUS_ERROR = 60,
  BUFFIO_ACCEPT_STATUS_SUCCESS = 61,
  BUFFIO_ACCEPT_STATUS_NA,
  BUFFFIO_ACCEPT_STATUS_NO_HANDLER,
};

enum BUFFIO_SOCKBROKER_STATE {
  BUFFIO_SOCKBROKER_INACTIVE = 71,
  BUFFIO_SOCKBROKER_ERROR,
  BUFFIO_SOCKBROKER_EPOLL,
  BUFFIO_SOCKBROKER_EPOLL_RUNNING,
  BUFFIO_SOCKBROKER_IO_URING,
  BUFFIO_SOCKBROKER_IO_URING_RUNNING,
};

//constexpr int BUFFIO_THREAD_NOT = 81;
//constexpr int BUFFIO_THREAD_RUNNING = 82;

enum BUFFIO_THREAD_STATUS {
  BUFFIO_THREAD_NOT = 81,
  BUFFIO_THREAD_RUNNING,
  BUFFIO_THREAD_KILLED = 83,
  BUFFIO_THREAD_DONE,
  BUFFIO_THREAD_ERROR,
  BUFFIO_THREAD_ERROR_MAP,
};

enum BUFFIO_SOCKBROKER_POLLER_TYPE{ 
  BUFFIO_POLLER_NONE = 91,
 /* The worker thread here is used as the event poller and publish work for other thread in the global queue
  * if a and every thread that dequeue from the queue alternate between the queue and the fd they have
  */
  BUFFIO_POLLER_MONOLITHIC,
  /*
  * This is used to create a seperate thread for epoll and workers on seperate thread
  * workers wait on a signal from the epoll to consome and wait sleep
  *  
  *  -- WORKERS CAN BE CONFIGURED TO BE ACTIVE AND CONSUME BY THE WORKER POLICY
  */

  BUFFIO_POLLER_MODULAR,
  BUFFIO_POLLER_IO_URING
};
enum BUFFIO_SOCKBROKER_WORKER_POLICY{
 BUFFIO_WORKER_POLICY_CONSUME = 101,
 BUFFIO_WORKER_POLICY_WAIT,
 BUFFIO_WORKER_POLICY_HYBRID
};

#endif
